/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:a3183180-fffa-4f1a-a9c8-a0206e3c9a56",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_6neHs1AlZ",
    "aws_user_pools_web_client_id": "4qbqcng53vvto9rnaddietpk3s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://nmo667nu7fdrpmnphbz5eewmdy.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2efrd2kgarc4bd3ckfnejb326u",
    "aws_user_files_s3_bucket": "awstutorial561b3b3803474019936677c2c6fce77005540-staging",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
